package net.myphenotype.jeeves.drools.section03.step1
 
import net.myphenotype.jeeves.drools.domain.Invoice;
import java.time.LocalDate;

rule "Valid Invoice"
  dialect "java"
  when
	$invoice:Invoice( !isExpired(), invoiceAmount > 0 )
  then
	System.out.println("This invoice with PO" + $invoice + " is READY FOR matching");
end

rule "Expired or zero amount invoice"
  dialect "java"
  when
	$invoice:Invoice( isExpired() || invoiceAmount == 0 )
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because it is not due yet or the invoice amount is zero" );
end
