package net.myphenotype.jeeves.drools.section07.step4

import net.myphenotype.jeeves.drools.domain.InvalidPassport;
import net.myphenotype.jeeves.drools.domain.InvalidVisaApplication;
import net.myphenotype.jeeves.drools.domain.Passport;
import net.myphenotype.jeeves.drools.domain.Visa;
import net.myphenotype.jeeves.drools.domain.VisaApplication;

rule "Issue visa for valid applications"
	dialect "java"
	when
	  $visaApplication: VisaApplication( )
	  $passport: Passport( this.passportNumber == $visaApplication.passportNumber )
	  not InvalidPassport( this.passport == $passport )
	  not InvalidVisaApplication( this.visaApplication == $visaApplication )
	then
	  Visa visa = new Visa( $passport.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insertLogical( visa );
end
