spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      format_sql: false
      show-sql: false
      generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled:
        debug: true
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: fromEmailID@outlook.com
    password: passwordPlease
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true