server:
  port: 8222

spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:order_db
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
