package net.myphenotype.jeeves.drools.section03.step2
 
import net.myphenotype.jeeves.drools.domain.Passport;
import java.time.LocalDate;

rule "Valid passport"
  dialect "java"
  when
	Passport( !isExpired(), unusedVisaPages > 0 )
  then
	System.out.println( "This passport is CORRECT" );
end

rule "Expired passport"
  dialect "java"
  when
	Passport( isExpired() )
  then
	System.out.println( "This passport is INVALID because it is expired" );
end

rule "Full passport"
  dialect "java"
  when
	Passport( unusedVisaPages == 0 )
  then
	System.out.println( "This passport is INVALID because it has no space for visa" );
end
