package net.myphenotype.jeeves.drools.section03.step3
 
import net.myphenotype.jeeves.drools.domain.Invoice;
import java.time.LocalDate;

rule "Valid Invoice"
  dialect "java"
  when
	$invoice:Invoice( !isExpired(), $invoiceAmt:invoiceAmount > 0 )
  then
	System.out.println("This invoice with PO" + $invoice + " is READY FOR matching. " + "An amount of $" + $invoiceAmt + " will be considered for matching" );
end

rule "Expired invoice"
  dialect "java"
  when
	$invoice:Invoice( isExpired())
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because it is not due yet" );
end

rule "Zero amount invoice"
  dialect "java"
  when
	$invoice:Invoice(invoiceAmount == 0 )
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because the invoice amount is zero" );
end
