package net.myphenotype.jeeves.drools.section07.step2
 
import net.myphenotype.jeeves.drools.domain.InvalidPassport;
import net.myphenotype.jeeves.drools.domain.ValidPassport;
import net.myphenotype.jeeves.drools.domain.Passport;
import net.myphenotype.jeeves.drools.domain.Validation;
import java.time.LocalDate;

rule "Valid passport"
	dialect "java"
	when
		$passport: Passport( )
		not( InvalidPassport( this.passport == $passport) )
	then
		System.out.println( $passport + " is not invalid, consider OK for now" );
		insertLogical( new ValidPassport($passport) );
end

rule "Expired passport"
	dialect "java"
	when
		$passport: Passport( isExpired()  )
	then
		System.out.println( $passport + " is INVALID because it is expired" );
		insert( new InvalidPassport($passport) );
end

rule "Full passport"
	dialect "java"
	when
		$passport: Passport( unusedVisaPages == 0   )
	then
		System.out.println( $passport + " is INVALID because it has no space for visa" );
		insert( new InvalidPassport($passport) );
end
