package net.myphenotype.jeeves.drools.section04.step1
 
import net.myphenotype.jeeves.drools.domain.Invoice;
import net.myphenotype.jeeves.drools.domain.Validation;
import java.time.LocalDate;

rule "Expired invoice"
  dialect "java"
  when
	$invoice:Invoice( isExpired())
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because it is not due yet" );
	modify($invoice) {
		  setValidation( Validation.HOLD )
	}
end

rule "Zero amount invoice"
  dialect "java"
  when
	$invoice:Invoice(invoiceAmount == 0 )
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because the invoice amount is zero" );
  	modify($invoice) {
		  setValidation( Validation.FAILED )
	}
end

rule "Valid Invoice"
  dialect "java"
  when
	$invoice:Invoice( validation == Validation.UNKNOWN  )
  then
	System.out.println("This invoice with PO" + $invoice + " has not violated any rules. It will be considered for matching" );
  	modify($invoice) {
		  setValidation( Validation.PASSED )
	};
	$invoice.setCause("Not Applicable");
end