spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/lib_one_to_many_bi?useSSL=false&serverTimezone=UTC
    username: hbstudent
    password: hbstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
debug: false