package net.myphenotype.jeeves.drools.section06.step5

import net.myphenotype.jeeves.drools.domain.Validation;
import net.myphenotype.jeeves.drools.domain.PurchaseOrder;
import net.myphenotype.jeeves.drools.domain.MatchingOutcome;
/*
Activation-group ensures that if one rule (any first) is activated (satisfied the condition) in that group, all others are cancelled (not even evaluated)
*/
rule "Report payments"
  dialect "java"
  activation-group "conclusion"
  salience 20
  when
    MatchingOutcome()
  then
    System.out.println("Conclusion: at least one payment instruction was issued");
end

rule "Report no payments"
  dialect "java"
  activation-group "conclusion"
  salience 10
  when
    PurchaseOrder( validation == Validation.FAILED )
  then
    System.out.println("Conclusion: no visas were issued");
end
