package net.myphenotype.jeeves.drools.section03.step5

import net.myphenotype.jeeves.drools.domain.Validation;
import net.myphenotype.jeeves.drools.domain.Invoice;
import java.time.LocalDate;

rule "Unknown Invoice State"
  dialect "java"
  when
	$invoice:Invoice( validation == Validation.UNKNOWN  )
  then
	System.out.println("This invoice with PO" + $invoice + " is not validated through the rules engine. It will be NOT considered for matching" );
  $invoice.setValidation( Validation.UNKNOWN );
end

rule "Expired invoice"
  dialect "java"
  when
	$invoice:Invoice( isExpired())
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because it is not due yet" );
  $invoice.setValidation( Validation.HOLD );
end

rule "Zero amount invoice"
  dialect "java"
  when
	$invoice:Invoice(invoiceAmount == 0 )
  then
	System.out.println( "This invoice with PO" + $invoice + " is NOT READY FOR MATCHING because the invoice amount is zero" );
  $invoice.setValidation( Validation.FAILED );
end