spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      format_sql: false
      show-sql: false
      generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled:
        debug: true
app:
  numberOfAccounts: 50